######################################################################
# Automatically generated by qmake (3.1) Wed May 29 08:35:29 2019
######################################################################

QMAKE_CXXFLAGS+= -g
# Directories
QT += widgets
QT += gui
HEADERS += ./src/*.h
SOURCES += ./src/*.cpp
OBJECTS_DIR = ./objects
